services:
  keycloak-postgres:
    image: postgres
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - keycloak-postgres
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/keycloak  
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password      
    ports:
      - "8080:8080"
    command: ["start-dev" , "--db", "postgres", "--db-url", "jdbc:postgresql://keycloak-postgres:5432/keycloak", "--db-username", "keycloak", "--db-password", "password"]